name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Test
        run: bazelisk test //test/...

  rules_apple_tests:
    name: rules_apple Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Run rules_apple Tests
        run: test/run_rules_apple_tests.sh
